apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kill-ai-leak.fullname" . }}-secret
  labels:
    {{- include "kill-ai-leak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.storage.postgresDSN }}
  postgres-dsn: {{ .Values.storage.postgresDSN | b64enc | quote }}
  {{- end }}
  {{- if .Values.alerting.slackUrl }}
  slack-url: {{ .Values.alerting.slackUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.alerting.webhookUrl }}
  webhook-url: {{ .Values.alerting.webhookUrl | b64enc | quote }}
  {{- end }}
